### ISSUE TITLE
Problem with v0.6.1-beta.1 integration

### ISSUE THREAD

**Issue by SpainBoys** [dan-r/HomeAssistant-NissanConnect#71]
**What happened?**
**Today, after updating the integration version to v0.6.1-beta.1 an integration error appeared.
Please help to solve this problem.
Before the update the integration version v0.6.0 worked fine.**

**Log Output**
Any relevant logs from Home Assistant.
`2024-11-07 09:38:16.035 INFO (MainThread) [custom_components.nissan_connect] Logging in to service
2024-11-07 09:38:18.638 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry -----@gmail.com for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 55, in async_setup_entry
    await hass.async_add_executor_job(vehicle.refresh)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/kamereon.py", line 865, in refresh
    self.fetch_all()
  File "/config/custom_components/nissan_connect/kamereon.py", line 870, in fetch_all
    self.fetch_battery_status()
  File "/config/custom_components/nissan_connect/kamereon.py", line 1163, in fetch_battery_status
    return self.fetch_battery_status_ariya()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/kamereon.py", line 1221, in fetch_battery_status_ariya
    battery_data = body['data']['attributes']
                   ~~~~^^^^^^^^
KeyError: 'data'
2024-11-07 09:38:29.817 INFO (MainThread) [custom_components.nissan_connect] Logging in to service
2024-11-07 09:38:30.295 DEBUG (MainThread) [custom_components.nissan_connect] Finding vehicles
2024-11-07 09:38:31.270 DEBUG (SyncWorker_40) [custom_components.nissan_connect.kamereon] Unknown feature 308
2024-11-07 09:38:31.270 DEBUG (SyncWorker_40) [custom_components.nissan_connect.kamereon] Unknown feature 420
2024-11-07 09:38:31.270 DEBUG (SyncWorker_40) [custom_components.nissan_connect.kamereon] Active features: [<Feature.BREAKDOWN_ASSISTANCE_CALL: '1'>, <Feature.MY_CAR_FINDER: '12'>, <Feature.MIL_ON_NOTIFICATION: '15'>, <Feature.VEHICLE_HEALTH_REPORT: '18'>, <Feature.APP_DOOR_LOCKING: '27'>, <Feature.APP_BASED_NAVIGATION: '35'>, <Feature.DESTINATION_SEND_TO_CAR: '37'>, <Feature.GOOGLE_PLACES_SEARCH: '40'>, <Feature.PREMIUM_TRAFFIC: '43'>, <Feature.MOBILE_INFORMATION: '74'>, <Feature.PERSONAL_DATA_SYNC: '80'>, <Feature.HORN_AND_LIGHTS: '97'>, <Feature.CURFEW_ALERT: '98'>, <Feature.MAINTENANCE_ALERT: '101'>, <Feature.VEHICLE_SOFTWARE_UPDATES: '107'>, <Feature.VEHICLE_STATUS_CHECK: '202'>, <Feature.NAVIGATION_FACTORY_RESET: '208'>, <Feature.VEHICLE_WIFI: '213'>, <Feature.NAVIGATION_MAP_UPDATES: '217'>, <Feature.LAST_MILE_NAVIGATION: '227'>, <Feature.GOOGLE_STREET_VIEW: '229'>, <Feature.GOOGLE_SATELITE_VIEW: '230'>, <Feature.DYNAMIC_EV_ICE_RANGE: '232'>, <Feature.ECO_ROUTE_CALCULATION: '233'>, <Feature.DRIVING_JOURNEY_HISTORY: '235'>, <Feature.ONLINE_PARKING_INFO: '243'>, <Feature.ONLINE_RESTAURANT_INFO: '244'>, <Feature.ONLINE_SPEED_RESTRICTION_INFO: '245'>, <Feature.WEATHER_INFO: '246'>, <Feature.VEHICLE_ACCESS_TO_EMAIL: '248'>, <Feature.VEHICLE_ACCESS_TO_MUSIC: '249'>, <Feature.VEHICLE_ACCESS_TO_CONTACTS: '262'>, <Feature.ZONE_ALERT: '281'>, <Feature.SPEEDING_ALERT: '282'>, <Feature.CHARGING_SPOT_INFO: '288'>, <Feature.CHARGING_START: '299'>, <Feature.CLIMATE_ON_OFF_NOTIFICATION: '311'>, <Feature.CHARGING_SPOT_SEARCH: '312'>, <Feature.PLUG_IN_REMINDER: '314'>, <Feature.CHARGING_STOP_NOTIFICATION: '317'>, <Feature.BATTERY_STATUS: '319'>, <Feature.VEHICLE_STATE_OF_CHARGE_PERCENT: '322'>, <Feature.DRIVING_ANALYSIS: '340'>, <Feature.CO2_GAS_SAVINGS: '341'>, <Feature.ELECTRICITY_FEE_CALCULATION: '342'>, <Feature.CHARGING_CONSUMPTION_HISTORY: '344'>, <Feature.BATTERY_MONITORING: '345'>, <Feature.BATTERY_DATA: '347'>, <Feature.CHARGING_SPOT_UPDATES: '354'>, <Feature.RECHARGEABLE_AREA: '358'>, <Feature.NO_CHARGING_SPOT_INFO: '359'>, <Feature.EV_RANGE: '360'>, <Feature.CLIMATE_ON_OFF: '366'>, <Feature.VIRTUAL_PERSONAL_ASSISTANT: '734'>, <Feature.ALEXA_ONBOARD_ASSISTANT: '736'>, <Feature.SCHEDULED_ROUTE_CLIMATE_CONTROL: '747'>, <Feature.SCHEDULED_ROUTE_CALENDAR_INTERGRATION: '819'>, <Feature.OWNER_MANUAL: '827'>, <Feature.LOCK_STATUS_CHECK: '2021'>, <Feature.TEMPERATURE: '2042'>, <Feature.VEHICLE_DATA: '2121'>, <Feature.VEHICLE_DATA_2: '2122'>]
2024-11-07 09:38:31.479 INFO (MainThread) [custom_components.huawei_solar] Fetching HV2230135175_inverter_data_update_coordinator data recovered
2024-11-07 09:38:32.381 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry -----@gmail.com for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 55, in async_setup_entry
    await hass.async_add_executor_job(vehicle.refresh)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/kamereon.py", line 865, in refresh
    self.fetch_all()
  File "/config/custom_components/nissan_connect/kamereon.py", line 870, in fetch_all
    self.fetch_battery_status()
  File "/config/custom_components/nissan_connect/kamereon.py", line 1163, in fetch_battery_status
    return self.fetch_battery_status_ariya()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/kamereon.py", line 1221, in fetch_battery_status_ariya
    battery_data = body['data']['attributes']
                   ~~~~^^^^^^^^
KeyError: 'data'
`
**Home Assistant Version**
Find this in Settings &gt; About.
**Core: 2024.11.0
Supervisor: 2024.11.2
Operating System: 13.2
User interface: 20241106.0**

**Integration Version**
**Find this from HACS.
Version:  2.0.1**

**Comment by dan-r** [comment]
What car do you have?

**Comment by SpainBoys** [comment]
>What car do you have?
**Nissan Ariya.**
I live in Spain.

**Comment by dan-r** [comment]
Would you mind testing beta 2?

**Comment by dan-r** [comment]
You should be able to see more entities with this change. These were reported as not showing for the Ariya before:
* Charge Time (3kW)
* Charge Time (6kW)
* Last Updated
* Range (AC Off)
* Range (AC On)

Do you see any difference from v0.6.0?

**Comment by SpainBoys** [comment]
> You should be able to see more entities with this change. These were reported as not showing for the Ariya before:
> 
> * Charge Time (3kW)
> * Charge Time (6kW)
> * Last Updated
> * Range (AC Off)
> * Range (AC On)
> 
> Do you see any difference from v0.6.0?
Here's everything your integration is displaying right now.
![image](https://github.com/user-attachments/assets/0d295e58-de11-4f9f-817b-029f50e44654)

**Comment by dan-r** [comment]
Good to hear - thanks for confirming!
